### ISSUE TITLE
Feature request: remove/reduce notifications

### ISSUE THREAD

**Issue by mikepqr** [gapop/pinboard-webextension#11]
I don't think a system notification letting me know I just created a bookmark is appropriate/necessary/useful. I know I just created a bookmark! :-)

Could you add a preference to disable it, or remove it entirely if you agree that it is not useful?

**Comment by gapop** [comment]
The setting you ask for already exists! Go to Preferences and uncheck _Show
notifications when saving links_. Then the extension will only show
notifications on rare events, like when saving a link has failed.

**Comment by mikepqr** [comment]
Ooof. Sorry! Thanks!
