### ISSUE TITLE
Have setting for opening in new tab rather than as popup?

### ISSUE THREAD

**Issue by voxpelli** [gapop/pinboard-webextension#12]
Popups work poorly with MacOS fullscreen applications, so I would rather open the pinboard page in a new tab, is it possible to add a setting for that option?

I might give this a stab myself

**Comment by gapop** [comment]
I’ll consider this for a future version.

**Comment by gapop** [comment]
@voxpelli, I’ve added this to version 1.61. I hope it works well for you.
