### ISSUE TITLE
Preferences don’t save

### ISSUE THREAD

**Issue by zachleat** [gapop/pinboard-webextension#2]
Trying to save this preference but it doesn’t do anything?
![image](https://user-images.githubusercontent.com/39355/33346794-7e9aec0e-d456-11e7-8695-598449cf09c4.png)

Just resets to `shows menu` every time.

**Comment by gapop** [comment]
Do you think you might have some other extension that could purge the browser storage? Some privacy extensions might do that.

Also, do you use my extension on more than one computer and do you use Firefox Sync? It's conceivable that some instance of Firefox is overriding the setting for the other.

**Comment by zachleat** [comment]
Hmm, I use these extensions:
<img width="369" alt="image" src="https://user-images.githubusercontent.com/39355/33413116-2da2efea-d555-11e7-897a-95fbf08b0886.png">

Maybe uBlock but I don’t think so?

No Firefox Sync.

Is it stored in localStorage or sessionStorage? I can use devtools to diagnose.

**Comment by gapop** [comment]
That rules out the causes I could think of.

Please tell me which exact version of Firefox you are using, and on which OS.

When you switch the toolbar button to "Shows 'Add Link' dialog", does the button still open a menu, or is it just that the dropdown menu in the preferences page doesn't show the current setting?

The preferences are stored in a special storage area for extensions. Within the context of the extension, this area can be accessed using the `browser.storage.sync` object. I don't know how to view it with the developer tools. I remember this was frustrating during development. If I could reproduce the bug, I would use the extension debugger and log the stored data to console to see what's going on.

Things you could try that might help:
- Uninstall and reinstall the extension
- [Create a new Firefox profile](https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles), install the extension in the new profile and see if the bug reproduces. If it doesn't, that would indicate some interference with the settings in your default profile.

**Comment by zachleat** [comment]
Really appreciate your help but unfortunately wasn’t able to get this working—sorry!

**Comment by gapop** [comment]
Thanks for reporting this and sorry I couldn't figure it out. I intend to make some changes to how preferences are stored in a future version. At that time I'll update this ticket, and if you're still subscribed, I hope you'll give it a second chance.

**Comment by zachleat** [comment]
Absolutely! 👍
