### ISSUE TITLE
Please add a link to starred bookmarks

### ISSUE THREAD

**Issue by patrikr** [gapop/pinboard-webextension#3]
Request: Please add a link to starred bookmarks (https://pinboard.in/u:xxxxxxxxx/starred/) in the drop down menu.

**Comment by gapop** [comment]
I couldn’t find a generic URL for the Starred filter, that is, one which doesn’t include the username. The extension doesn’t know your username. So I can’t easily fulfill your request at this time. However, I’ll keep this on the to-do list.
