### ISSUE TITLE
Request: save link from Reader View (if possible)

### ISSUE THREAD

**Issue by francisbarton** [gapop/pinboard-webextension#4]
I've noticed that when I am viewing a page in Firefox's Reader View, although the URL remains the same in the address bar, when I try to save the page using Pinboard Web Extension the save does not work. The menu from the toolbar icon activates OK. But nothing is added to my pinboard.
Similarly if I use the right-click menu and for example select "Read later", I get a notification bubble saying the link has been saved but nothing is actually saved.
If it's possible, it would be great to be able to save from Reader View, rather than having to go back to the normal page view in order to save to pinboard.
Thank you!

**Comment by gapop** [comment]
Thanks for writing. I haven’t thought of this. I am working on it and should have it ready some time next week.

**Comment by francisbarton** [comment]
It's ok really, all one has to do is Ctrl-C Ctrl-V the URL into the
pinboard pop-up and you're away. But if it's fixable, it's one step fewer.
Thanks.

**Comment by gapop** [comment]
This was implemented in version 1.32, currently available from Mozilla Add-ons. Just upgrade from within your browser.

There is a limitation in Reader mode, due to a constraint in the Firefox extension API: the Description cannot be pre-filled with selected text from the page.
