### ISSUE TITLE
Prevent duplicates

### ISSUE THREAD

**Issue by kaushalmodi** [gapop/pinboard-webextension#5]
Hello,

It has happened few times that I try to save a link using your pinboard extension, but I also happen to have saved it earlier.

In that case, it creates a duplicate bookmark in my pinboard account.

Instead, if a link is already found, can you pop-up the Edit interface for that saved link?

Many thanks for developing and maintaining this extension!

**Comment by kaushalmodi** [comment]
Actually, please ignore this.. looks like it **does** open the Edit interface for a pre-saved link..

Either this got fixed recently (past month?) or I am confusing with the Android Pinboard app :)

**Comment by gapop** [comment]
Yeah, it should not create duplicates. This was never a problem with my extension. Pinboard actually does the saving. The extension simply loads the save/edit form from Pinboard, so the behavior is determined by Pinboard.
