### ISSUE TITLE
Option to not show all tags on Save to Pinboard pop-up

### ISSUE THREAD

**Issue by armen52** [gapop/pinboard-webextension#6]
Would you consider exposing a setting to not show all our tags in the save pop-up window? 

For example, today the extension pops open this window when I choose to "Save to Pinboard": https://pinboard.in/add?showtags=yes&url=https%3A%2F%2Faddons.mozilla.org%2Fen-US%2Ffirefox%2Faddon%2Fpinboard-webextension%2F%3Fsrc%3Dsearch&title=Pinboard WebExtension %E2%80%93 Add-ons for Firefox&description=

What I am suggesting is an option to use this alternative version of the save form instead: https://pinboard.in/add?url=https%3A%2F%2Faddons.mozilla.org%2Fen-US%2Ffirefox%2Faddon%2Fpinboard-webextension%2F%3Fsrc%3Dsearch&title=Pinboard WebExtension %E2%80%93 Add-ons for Firefox&description=

It's just about dropping the showtags=yes query parameter. 

Otherwise, great work on the updated extension. Recently switched back to Firefox from Chrome and it's very handy. Thanks!

**Comment by gapop** [comment]
Okay, I'll add this. Thanks for doing the research. Stay subscribed to this thread, I'll update it when I've added the feature.

**Comment by gapop** [comment]
@armen52 implemented this himself!
