### ISSUE TITLE
Feature request: keyboard shortcut to save current page directly

### ISSUE THREAD

**Issue by francisbarton** [gapop/pinboard-webextension#9]
No big deal but it would be nice to have the option to use a keyboard shortcut to quickly pin the current page (or to open the save link dialog, whatever - maybe based on what is already set in the options for what happens when you click on the toolbar button?)

I can see in the add-on details that "keyboard shortcut support in Firefox's new add-on platform is inadequate" - so of course you should wait until this improves. Any news on when this platform improvement might arrive?

I thought it worth posting an issue anyway, as a way of saying that the addition of a keyboard shortcut would be appreciated, when possible.

Happy user of this add-on, still - thank you!

**Comment by gapop** [comment]
Platform support has improved and I am almost done with the feature. I'll
update this ticket when the new version is released, likely next week.

**Comment by jimmerricks** [comment]
I would really love to see this feature as well.

**Comment by gapop** [comment]
I have added this feature. Please update to the latest version. There are no shortcuts assigned by default, but you can assign the ones that you want in the Firefox extension shortcuts page.

Sorry for the delay!
